version: "3"
services:
  geartable:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD: 'local'
    image: geartable:1.0
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      DEBUG: 'true'
      SECURITY_SALT: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      DATABASE_URL: mysql://devuser:devpass@131.31.1.2/geartable
      DDB_REGION: ap-south-1
      DDB_VERSION: latest
      OAUTHAPP_GITHUB_CLIENT_ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      OAUTHAPP_GITHUB_CLIENT_SECRET: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      OAUTHAPP_GITHUB_REDIRECT_URI: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      SENTRY_DSN: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      AWS_ACCESS_KEY_ID: XXXXXXXXXXXXXX
      AWS_SECRET_ACCESS_KEY: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    networks:
      gear_net:
        ipv4_address: 131.31.1.1

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: geartable
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - 9906:3306
    networks:
      gear_net:
        ipv4_address: 131.31.1.2
volumes:
  db_data: {}
networks:
  gear_net:
    ipam:
      driver: default
      config:
        - subnet: 131.31.0.0/16
